[versions]

glideCompose = "1.0.0-alpha.1"
coreKtx = "1.10.1"
lifeCycleKtx = "2.6.1"
activityCompose = "1.7.1"
compose = "1.4.3"
material3 = "1.1.0"
hilt = "2.44"
junit = "4.13.2"
androidJunit = "1.1.4"
espresso = "3.5.0"
kotlin = "1.8.10"
android = "7.3.1"
kapt = "1.7.10"

[plugins]

#kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
android = { id = "com.android.application", version.ref = "android"}
androidLibrary = { id = "com.android.library", version.ref = "android"}

[libraries]


[bundles]